[project]
channels = ["conda-forge"]
name = "iss-profile-collection"
platforms = ["linux-64"]
version = "2025.3.0"

[system-requirements]
libc = "2.17"

[feature.profile.dependencies]
bluesky-base = "*"
bluesky-queueserver = "*"
matplotlib-base= ">=3.9.3,<4"
networkx = ">=3.4.2,<4"
nslsii = ">=0.11.2,<0.12"
numpy = "*"
ophyd = "*"
pyepics = "*"
python = ">=3.12,<3.13"
semver = ">=3.0.4,<4"
tiled-client = ">=0.1.0b11,<0.2"

# needed until we get p4p packaged
nose2 = ">=0.9.2,<0.10"
ply = ">=3.11,<4"
# needed until we get ophyd-async packaged
colorlog = ">=6.9.0,<7"
epicscorelibs = "*"
pydantic-numpy = "*"
xraydb = ">=4.5.8,<5"
pyqt = "<6"
lmfit = ">=1.3.4,<2"
interpolation = ">=2.2.7,<3"
scikit-learn = ">=1.7.1,<2"
periodictable = ">=1.7.1,<2"
xraylarch = "<1"
bluesky-kafka = ">=0.10.0,<0.11"
larixite = ">=2024.10.0,<2025"
aiohttp = ">=3.12.15,<4"
slackclient = ">=2.9.3,<3"
pyzbar = ">=0.1.9,<0.2"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"


[feature.profile.pypi-dependencies]
ophyd-async = { version = ">=0.9.0, <0.10", extras = ["ca", "pva"] }
# TODO get updated version built on CF
xas = { git = "https://github.com/nsls-ii-iss/xas" }
# TODO merge PR + get on CF
isstools = { git = "https://github.com/nsls-ii-iss/isstools", rev = "eb715eaa6436097cf88cf0a8f875fa1251f64657" }
# TODO make importable without I/O and get on CF
piezo-feedback = { git = "https://github.com/nsls-ii-iss/piezo-feedback" }


[feature.qs.dependencies]
bluesky-queueserver = "*"
bluesky-httpserver = "*"

[feature.qs.tasks]
# This section needs some development work to understand the best way to
# thread the required configuration through both the task and files checked into
# the profile.  These will interact with the ansible roles for pushing out the
# systemd units
qs-backend = "start-re-manager --profile-dir=."
qs-server = "uvicorn --host localhost --port 60610 bluesky_httpserver.server:app"


[feature.terminal.dependencies]
ipython = "*"
pyside6 = "*"


[feature.terminal.tasks]
start = "ipython --profile-dir=."
pvs = "ipython --profile-dir=. -c 'get_pv_types(); exit()'"

[environments]
terminal = {features=["profile", "terminal"], solve-group="profile"}
qs = {features=["profile", "qs"], solve-group="profile"}
